<?xml version="1.0" encoding="utf-8"?>

<Project Sdk="Dalamud.NET.Sdk/15.0.0">

  <PropertyGroup>

    <Version>1.1.0.5</Version>
    <FileVersion>1.1.0.5</FileVersion>
    <AssemblyVersion>1.1.0.5</AssemblyVersion>

    <PackageProjectUrl>https://github.com/McVaxius/FrenRider</PackageProjectUrl>

    <PackageLicenseExpression>AGPL-3.0-or-later</PackageLicenseExpression>

    <IsPackable>false</IsPackable>

  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ECommons" Version="3.2.0.17" />
  </ItemGroup>

  <ItemGroup>
    <None Include="images\icon.png" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="data\bm\**">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="videos\**">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <Target Name="CopyPluginArtifacts" AfterTargets="Build">

    <PropertyGroup>

      <PluginOutput>$(OutputPath)$(AssemblyName)</PluginOutput>

    </PropertyGroup>



    <MakeDir Directories="$(PluginOutput)" />



    <ItemGroup>

      <PluginFiles Include="$(TargetPath)" />

      <PluginFiles Include="$(ProjectDir)$(AssemblyName).json" />

      <PluginFiles Include="videos\**" />

      <PluginDataFiles Include="data\bm\**" />

    </ItemGroup>

    <Copy SourceFiles="@(PluginFiles)"

          DestinationFolder="$(PluginOutput)" />

    <Copy SourceFiles="@(PluginDataFiles)"

          DestinationFiles="@(PluginDataFiles->'$(PluginOutput)\data\bm\%(RecursiveDir)%(Filename)%(Extension)')" />

  </Target>

</Project>

